### ISSUE TITLE
Support for multiple tags

### ISSUE THREAD

**Issue by vsimplea** [damienaicheh/azure-devops-mobile-versioning#17]
Hello @damienaicheh ,

First, I would like to thank you for this amazing plugin for Azure DevOps Pipelines, it has been very helpful.

I'm facing an issue where on a commit I have more than 2 tags and the following code only retrieves one of them:
```yml
 - task: ExtractVersionFromTag@1
      displayName: 'Get git tag version'
      inputs:
        projectFolderPath: '$(Build.SourcesDirectory)'
```

For example on my commit I have multiple tags like: "build-ios" "v2.0.0-1" "staging", however, the YAML tasks get only the first tag "build-ios" instead of the one starting with "v" or the version number itself. 

Do you know if it is possible to get the version when multiple tags are assigned to the commit?

Thanks in advance!
