### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by larsa2000** [damienaicheh/azure-devops-mobile-versioning#5]
I can't get ExtractVersionFromTag to work. Tried adding this code, didn't do anything else. 

```
trigger:
- develop

pool:
  vmImage: 'macos-latest'

variables:
  outputDirectory: '$(build.binariesDirectory)'

steps:
# Get and set versions in Info.plist
- task: ExtractVersionFromTag@1
  inputs:
    projectFolderPath: '$(Build.SourcesDirectory)'

```
The Run failes with 
Cannot read property 'includes' of undefined

Did I miss something?

Regards//Lars
